-- FCRB Eventos - Supabase/PostgreSQL schema
-- Versioned reference for the MVP database.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  role text not null default 'gestor_eventos',
  department text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  official_name text not null,
  event_type text not null,
  event_date date not null,
  start_time time,
  end_time time,
  location text,
  format text not null default 'presencial',
  responsible_area text,
  lead_user_id bigint references public.users(id) on delete set null,
  short_description text,
  full_description text,
  target_audience text,
  accessibility_needs text,
  estimated_budget_cents integer not null default 0,
  status text not null default 'em_planejamento',
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_format_check check (format in ('presencial', 'online', 'hibrido')),
  constraint events_status_check check (
    status in (
      'em_planejamento',
      'em_andamento',
      'concluido',
      'cancelado',
      'arquivado'
    )
  ),
  constraint events_budget_check check (estimated_budget_cents >= 0)
);

create table if not exists public.checklist_items (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  title text not null,
  area text not null,
  status text not null default 'pendente',
  owner_user_id bigint references public.users(id) on delete set null,
  due_date date,
  notes text,
  source_document_id bigint,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint checklist_items_status_check check (
    status in (
      'nao_iniciado',
      'pendente',
      'em_andamento',
      'concluido',
      'atrasado',
      'cancelado'
    )
  )
);

create table if not exists public.communication_requests (
  id bigint generated by default as identity primary key,
  event_id bigint not null unique references public.events(id) on delete cascade,
  status text not null default 'nao_solicitado',
  collection_owner_id bigint references public.users(id) on delete set null,
  communication_owner_id bigint references public.users(id) on delete set null,
  inputs_due_date date,
  publication_due_date date,
  completion_percent integer not null default 0,
  title text,
  short_description text,
  full_description text,
  piece_type text,
  objective text,
  audience text,
  registration_link text,
  streaming_link text,
  channels text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint communication_requests_status_check check (
    status in (
      'nao_solicitado',
      'aguardando_briefing',
      'aguardando_informacoes',
      'insumos_incompletos',
      'pronto_para_comunicacao',
      'em_criacao',
      'em_revisao',
      'aprovado',
      'publicado'
    )
  ),
  constraint communication_requests_completion_check check (
    completion_percent between 0 and 100
  )
);

create table if not exists public.event_documents (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  title text not null,
  document_type text,
  category text,
  origin text not null default 'registro_vazio',
  status text not null default 'aguardando_criacao',
  owner_user_id bigint references public.users(id) on delete set null,
  responsible_area text,
  due_date date,
  access_level text not null default 'interno',
  version text not null default 'v1.0',
  file_label text,
  file_url text,
  notes text,
  source_draft_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_documents_origin_check check (
    origin in ('registro_vazio', 'upload', 'link', 'modelo', 'ia')
  ),
  constraint event_documents_status_check check (
    status in (
      'aguardando_criacao',
      'em_elaboracao',
      'minuta_gerada',
      'em_revisao',
      'aguardando_aprovacao',
      'aprovado',
      'enviado',
      'arquivado'
    )
  ),
  constraint event_documents_access_level_check check (
    access_level in ('publico', 'interno', 'restrito', 'sensivel')
  )
);

create table if not exists public.document_ai_drafts (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  document_id bigint references public.event_documents(id) on delete set null,
  draft_type text not null,
  model text not null,
  prompt_context text not null,
  generated_text text not null,
  subject text,
  pending_fields text,
  recommendations text,
  status text not null default 'minuta_gerada',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint document_ai_drafts_status_check check (
    status in ('minuta_gerada', 'salva_como_minuta', 'enviada_para_revisao')
  )
);

alter table public.event_documents
  add constraint event_documents_source_draft_id_fkey
  foreign key (source_draft_id)
  references public.document_ai_drafts(id)
  on delete set null;

alter table public.checklist_items
  add constraint checklist_items_source_document_id_fkey
  foreign key (source_document_id)
  references public.event_documents(id)
  on delete set null;

create table if not exists public.document_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  document_type text,
  description text,
  body_template text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_template_usage (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  template_id bigint not null references public.document_templates(id) on delete restrict,
  document_id bigint references public.event_documents(id) on delete set null,
  used_by_user_id bigint references public.users(id) on delete set null,
  used_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events(id) on delete cascade,
  actor_user_id bigint references public.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_events_status
  on public.events(status);

create index if not exists idx_events_event_date
  on public.events(event_date);

create index if not exists idx_events_responsible_area
  on public.events(responsible_area);

create index if not exists idx_checklist_items_event_status
  on public.checklist_items(event_id, status);

create index if not exists idx_checklist_items_event_due_date
  on public.checklist_items(event_id, due_date);

create index if not exists idx_communication_requests_event
  on public.communication_requests(event_id);

create index if not exists idx_event_documents_event_status
  on public.event_documents(event_id, status);

create index if not exists idx_event_documents_event_category
  on public.event_documents(event_id, category);

create index if not exists idx_document_ai_drafts_event_created
  on public.document_ai_drafts(event_id, created_at desc);

create index if not exists idx_event_template_usage_event
  on public.event_template_usage(event_id, used_at desc);

create index if not exists idx_audit_log_event_created
  on public.audit_log(event_id, created_at desc);
